const CLIENTES = [
  { id: 1, endereco: "MARIO LUNARDI, 130, CHARQUEADAS, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 2, endereco: "R. Alexandre Peretti, 154, CHARQUEADAS, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 3, endereco: "ANTONIO SUSIN, 191, CHARQUEADAS, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 4, endereco: "JOAO RIZZO, 1077, CHARQUEADAS, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 5, endereco: "ANTONIO SUSIN, 322, CHARQUEADAS, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 6, endereco: "R. Almerinda Ramos Santos, 208, CHARQUEADAS, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 7, endereco: "EUCLIDES MEDEIROS, 271, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 8, endereco: "DOUTORA BEATRIZ BEDIN, 255, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 9, endereco: "DOUTORA BEATRIZ BEDIN, 255, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 10, endereco: "R. Joanna Toscana Mezzomo Lora, 902, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 11, endereco: "ADELINO ANGELO CEGONI, 325, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 12, endereco: "SEVERINA BONETTO, 150, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 13, endereco: "R Alexandre Luciano, 956, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 14, endereco: "R Ernesto Bernardi, 1443, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 15, endereco: "R Alexandre Luciano, 956, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 16, endereco: "ANGELO ZULIAN SOBRINO, 1410, ESPLANADA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 17, endereco: "RUA GALEZZO PAGANELLI, 280, ESPLANADA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 18, endereco: "DIONYSIO ADAMI, 430, ESPLANADA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 19, endereco: "GALEZZO PAGANELLI, 280, ESPLANADA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 20, endereco: "R. Hygino Tartarotti, 421, ESPLANADA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 21, endereco: "LUIZ LAVRATTI, 1150, ESPLANADA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 22, endereco: "IRMA GENI, 870, ESPLANADA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 23, endereco: "R. Dionysio Adami, 430, ESPLANADA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 24, endereco: "DIONYSIO ADAMI, 241, ESPLANADA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 25, endereco: "R Sarmento Leite, 3488, Exposição, Caxias do Sul, RS, Brasil", lat: null, lon: null },
  { id: 26, endereco: "ANTONIO GATTERMANN, 2204, KAYSER, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 27, endereco: "SAO FRANCISCO DE PAULA, 725, KAYSER, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 28, endereco: "BOM JESUS, 1289, KAYSER, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 29, endereco: "R Ernesto Casara, 123, KAYSER, Caxias do Sul, RS, Brasil", lat: null, lon: null },
  { id: 30, endereco: "FRANCISCO FAGUNDES DA SILVA, 30, KAYSER, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 31, endereco: "Rua Gaetano Finco, 2125, KAYSER, Caxias do Sul, RS, Brasil", lat: null, lon: null },
  { id: 32, endereco: "Tv S Marcos, 345, KAYSER, Caxias do Sul, RS, Brasil", lat: null, lon: null },
  { id: 33, endereco: "R N Sra Aparecida, 610, Medianeira, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 34, endereco: "Rua Dionysio Adami, 430, Nossa Senhora das Graças, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 35, endereco: "Rua Eduardo Castilhos dos Reis, 42, Nossa Senhora das Graças, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 36, endereco: "ANDRADINA FORTUNATO DA SILVA, 1150, NOSSA SRA DAS GRACAS, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 37, endereco: "R. das Ametistas, 96, Nossa Sra. Das Gracas, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 38, endereco: "R. Dionysio Adami, 741, Nossa Sra. das Graças, Caxias do Sul, RS, Brasil", lat: null, lon: null },
  { id: 39, endereco: "R. Bonfíglio Tamagno, 1091, Nossa Sra. das Graças, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 40, endereco: "LUIZ ANTUNES, 267, PANAZZOLO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 41, endereco: "LUIZ ANTUNES 00906501, 906, PANAZZOLO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 42, endereco: "LUIZ BURATTO, 47, RIO BRANCO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 43, endereco: "WALTER CARLOS AFFONSO, 265, SALGADO FILHO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 44, endereco: "VITORIO MADALOSSO, 255, SALGADO FILHO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 45, endereco: "FLAVIO CHAVES, 605, SALGADO FILHO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 46, endereco: "Rua Jacintho Zanol, 280, Santa Corona, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 47, endereco: "NATAL BONADEO, 127, SAO LEOPOLDO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 48, endereco: "ERNA SIRTOLI UEZ, 1664, SAO LEOPOLDO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 49, endereco: "MARLENE ELZA PANAROTTO, 303, SAO VICTOR COHAB, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },

  { id: 50, endereco: "PINHEIROS, 849, BRANDALISE, Caxias do Sul, RS, Brasil", lat: null, lon: null },
  { id: 51, endereco: "ANGELINO FEIJO BASTOS, 379, Cidade Nova, Caxias do Sul, RS, Brasil", lat: null, lon: null },
  { id: 52, endereco: "R Claudiomar da Cruz, 117, Cidade Nova, Caxias do Sul, RS, Brasil", lat: null, lon: null },
  { id: 53, endereco: "PEDRO SEGALLA, 383, CINQUENTENARIO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 54, endereco: "Rua Emílio Fonini, 358, CINQUENTENARIO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 55, endereco: "R. Alceu Vamosi, 556, CINQUENTENARIO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 56, endereco: "R. Alceu Vamosi, 626, CINQUENTENARIO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 57, endereco: "R. Moacir Alves Brito, 76, DESVIO RIZZO, Caxias do Sul, RS, Brasil", lat: null, lon: null },
  { id: 58, endereco: "Rua Armando Salvador, 513, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 59, endereco: "R LEOCLIDES P DIAS, 245, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 60, endereco: "R. Nelsom Guerra Fogaça, 183, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 61, endereco: "ADEMAR ANGELIN DE ALMEIDA, 1042, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 62, endereco: "CARLOS FABRIS, 319, DESVIO RIZZO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 63, endereco: "MARIO VERONA, 180, MARECHAL FLORIANO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 64, endereco: "DAS VIOLETAS, 85, MARECHAL FLORIANO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 65, endereco: "Rua Nico Pires, 1065, MARECHAL FLORIANO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 66, endereco: "R Walfrida Versteg, 570, MARECHAL FLORIANO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 67, endereco: "CLAUDINO JOSE COVOLAN, 274, MARECHAL FLORIANO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 68, endereco: "Rua Paim Filho, 169, MARECHAL FLORIANO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 69, endereco: "Estr. Mun. Pedro Dedavid, 977, Matioda, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 70, endereco: "Rua Vinte de Setembro, 3459, Nossa Senhora de Lourdes, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 71, endereco: "Rua Guido Schio, 109, PIO X, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 72, endereco: "FERNANDO ADOLFO LOPES, 406, PIONEIRO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 73, endereco: "R. Frederico Bergman, 3096, PIONEIRO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 74, endereco: "BELMIRO ZANROSSO, 231, PIONEIRO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 75, endereco: "R. Nicanor Soares Antunes, 1269, PIONEIRO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 76, endereco: "GIACOMO SALVADOR, 3216, PIONEIRO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 77, endereco: "R Venâncio A Guaresi, 150, Pôr do Sol, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 78, endereco: "R. Gentil Antunes de Albuquerque, 71, Reolon, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 79, endereco: "GUIOMAR DAS NEVES, 120, Reolon, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 80, endereco: "GUIOMAR DAS NEVES, 210, Reolon, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 81, endereco: "GUIOMAR DAS NEVES, 153, Reolon, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 82, endereco: "LAURINDA PALANDI, 326, Reolon, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 83, endereco: "Rua Carolina Amância Soares, 300, Reolon, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 84, endereco: "PROFESSOR MARCOS MARTINI, 1299, SANTA CATARINA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 85, endereco: "Rua Oswaldo Cruz, 1473, SANTA CATARINA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 86, endereco: "R Balduíno D Arrigo, 423, SANTA CATARINA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 87, endereco: "R Matteo Gianella, 1037, SANTA CATARINA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 88, endereco: "RUA OSVALDO CRUZ, 1545, SANTA CATARINA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 89, endereco: "R Benedicto Venturini, 698, SANTA CATARINA, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 90, endereco: "GILBERTO CANDEIA, 644, Santa Lúcia, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 91, endereco: "JACOB LUCHESI, 2534, Santa Lúcia, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 92, endereco: "Rua José Constant Lazzari, 214, São Giácomo, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 93, endereco: "Rua Maravilha, 1115, São Giácomo, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 94, endereco: "PIO XII, 92, SAO JOSE, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 95, endereco: "PROFESSORA HONORINO SOARES DUTRA, 177, SAO JOSE, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 96, endereco: "Rua Evaristo de Antoni, 3122, SAO JOSE, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 97, endereco: "R Hugo L Ronca, 2720, São José, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 98, endereco: "Rua João Batista Montanari, 15, São José, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null },
  { id: 99, endereco: "AVENIDA RUBEN BENTO ALVES, 2101, UNIVERSITARIO, CAXIAS DO SUL, RS, Brasil", lat: null, lon: null }
];

const INITIAL = CLIENTES.map(cliente => ({ ...cliente }));
